### ISSUE TITLE
drop-down menu or list for Marker Color in GSheet

### ISSUE THREAD

**Issue by JackDougherty** [HandsOnDataViz/leaflet-maps-with-google-sheets#114]
We used to have a drop-down menu for Marker Color, but it disappeared from the GS template
https://docs.google.com/spreadsheets/d/1ZxvU8eGyuN9M8GxTU9acKVJv70iC3px_m3EVFsOHN9g/edit#gid=0

Or maybe we got rid of it to increase flexibility?

Should we restore the drop-down menu? If not, is there a list of standard color names that work, which I could place in the tutorial?

<img width="114" alt="marker-color-menu" src="https://user-images.githubusercontent.com/649719/89658141-283ff780-d89c-11ea-9600-90a25237b778.png">

**Comment by ilyankou** [comment]
@JackDougherty 

We made markers SVG to allow any color combination. See [this commit](https://github.com/HandsOnDataViz/leaflet-maps-with-google-sheets/commit/5e3ca41fd7607494ab3fe2c8292be1d74e97e37a). Most browsers will support the following color names: https://www.w3schools.com/colors/colors_names.asp

**Comment by JackDougherty** [comment]
perfect! Sorry I forgot about this.
