### ISSUE TITLE
Group icons do not appear in legend with code for GS v4?

### ISSUE THREAD

**Issue by JackDougherty** [HandsOnDataViz/leaflet-maps-with-google-sheets#116]
Another issue popped up during testing. In the new code for GS v4, Group icons for points do not appear in the legend (on the right side of the screen) but they do in the GS v3 code (on the left side).

<img width="867" alt="group-icon" src="https://user-images.githubusercontent.com/649719/89670022-79f17d80-d8ae-11ea-92ec-e28fb7a2ba08.png">

**Comment by ilyankou** [comment]
Fixed now!
