### ISSUE TITLE
please look for Options.csv at root level, not CSV folder

### ISSUE THREAD

**Issue by JackDougherty** [HandsOnDataViz/leaflet-maps-with-google-sheets#117]
In the new code, please change this line:
```   
$.ajax({
       url:'csv/Options.csv',
```
https://github.com/HandsOnDemo/leafletmaps4/blob/google_v4/scripts/map.js#L973

I'd like the code to look for Options.csv at the root level of the repo, NOT in a separate CSV folder. I want to make these instructions as simple as possible for users to follow, and it's not obvious how to create subfolders in the GitHub web interface. So root level would be best.

thanks

**Comment by JackDougherty** [comment]
and also this line:
https://github.com/HandsOnDataViz/leaflet-maps-with-google-sheets/blob/google_v4/scripts/procsv.js#L13

**Comment by ilyankou** [comment]
Done!
