### ISSUE TITLE
preparing for next version

### ISSUE THREAD

**Issue by JackDougherty** [HandsOnDataViz/leaflet-maps-with-google-sheets#120]
@ilyankou - here's what I did today to prepare for the next official release of our code

- updated CDNs to most recent versions
- updated README to reflect changes above, plus new info about options
- moved old leaflet-providers.js script to `archived` folder since newer CDN addresses Carto https secure issue
- removed our Geocoder script from linked Google Sheet, since README now recommends new Geocoder add-on

Would you please review my work, and do the following?
- I think we need to remove all Mapzen references (since it shut down https://www.mapzen.com/blog/shutdown/) from Google Sheet (see Options tab, rows 19 and 20) and the code. Confirm that you replaced everything with other leaflet search
- if you have time, add Google Analytics tracking to Google Sheet Options and code
- delete the `archived` folder if we don't need it
- remove the Google v4 branch, since it confuses new users to have multiple branches in this repo
- change the release number in both GitHub and the linked Google Sheet

Let me know if you have any questions. I'll start working on Leaflet Storymaps next...

**Comment by JackDougherty** [comment]
@ilyankou - now that we're approaching the finish line with the new version of this code, here's a two more ideas, intended to simplify things for users. Let me know what you think

1. How do you feel about removing the `markers` folder and moving all content into the `media` folder? I found this to be helpful when working with users, to keep all of their media uploads in one folder. If you agree, then I believe we only need to change this in the Google Sheet.

2. How do you feel about renaming the `geometry` folder to be `geodata` or `geojson`? Either one would be more accurate. But I don't want to make changes that break backwards compatibility unless they are good ones.

**Comment by ilyankou** [comment]
All done. Please verify when you get a chance, and close this comment if all seems ok.
