### ISSUE TITLE
let's continue to use CSV folder

### ISSUE THREAD

**Issue by JackDougherty** [HandsOnDataViz/leaflet-maps-with-google-sheets#122]
@ilyankou  -- sorry to go back and forth on this, but now I'm convinced we should continue using the `csv` folder, rather than telling users to place those files at the root level.

The main reason is consistency in our instructions. I'm realizing that it's easier to tell all users how to create a csv folder and place their files there, rather than giving different instructions for pre-Sept2020 vs post-Sept2020 users. 

When we diagnose issues, you and I can instantly see whether or not they've created a csv folder, so I don't think there's really any added benefit to placing those files at the root level, where it will clutter up things.

Please let me know what you think, and if you agree, then we'll change the text in the README and the book to be consistent.

**Comment by ilyankou** [comment]
I agree, it is much neater when all CSV files are in a single folder.
