### ISSUE TITLE
Points: icons are colored in wrong order in legend

### ISSUE THREAD

**Issue by ilyankou** [HandsOnDataViz/leaflet-maps-with-google-sheets#124]
Double-check with Groups column sorted non-alphabetically.

**Comment by JackDougherty** [comment]
I don't have strong feelings about this. My vague memory is that we may have intentionally sorted groups by their order of appearance in the Points sheet to allow for non-alphabetical order. Let me know if you recommend a different approach

**Comment by ilyankou** [comment]
I took a closer look and there appears to be a bug due to JavaScript object order handling. When group names such as `4` are converted to numbers from strings, they stop adhering to the insert order when colors object is generated. Pushed changes to fix the issue. Thanks @jonestrn
