### ISSUE TITLE
known issue: Chrome console error due to lack of favicon

### ISSUE THREAD

**Issue by JackDougherty** [HandsOnDataViz/leaflet-maps-with-google-sheets#16]
Create favicon and insert in index.html

```
  <head>
  <link rel="icon" type="image/png" href="src/favicon.png">
```

**Comment by ilyankou** [comment]
Let me know what you think of the [favicon with the bird from the book cover](https://handsondataviz.github.io/leaflet-maps-with-google-sheets/):
![favicon](https://user-images.githubusercontent.com/10443203/92920540-592ac380-f42a-11ea-9d1e-59c2358e45e7.png)

**Comment by JackDougherty** [comment]
Wow - I love the concept of tying the favicon to the book cover image! But is the tiny image clear to readers' eyes? Please show the favicon to a few people who know, with a better sense of design than me, and see what they think. Thanks!

**Comment by ilyankou** [comment]
I adjusted the size ('zoomed in' and re-positioned) so the beak is easier to recognize. I looked at it on Retina and a large, less cool desktop, and it looks recognizable. Let's keep it and see how it goes.

P.S. You may need to clear cache / view in private browsing to see the updated favicon.
![favicon](https://user-images.githubusercontent.com/10443203/92932705-2a6a1880-f43d-11ea-8a41-78e86bfbb603.png)
